name: Create new branch

on:
  repository_dispatch:
    types:
      - feature_create

jobs:
  run:
    name: Run check
    runs-on: ubuntu-latest

    steps:
      - name: set Today Date
        run: |
          echo TODAY_DATE=$(date +%Y년\ %m월\ %d일\ %H시\ %M분\ %s초) >> $GITHUB_ENV
          echo FEATURE_BRANCH="feature/${{ github.event.client_payload.jiranumber }}/base" >> $GITHUB_ENV
          echo ${{ env.FEATURE_BRANCH }}
          
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Version Update
        run: |
          echo "AMONDZ_APP_VERSION = ${{ github.event.client_payload.version }}"
      
      - name: new commit actions
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 
          create_branch: true
          branch: "feature/${{ github.event.client_payload.jiranumber }}/base"
