on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
          
      #- name: Set output
      #  id: vars
      #  run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        
      #- name: Check output
      #  env:
      #    RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      #  run: |
      #    echo $RELEASE_VERSION
      #    echo ${{ steps.vars.outputs.tag }}

      - name: Create local branch
        run: |
          git checkout -b "update/v${{ steps.vars.outputs.tag }}"
          
      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          branch: "update/v${{ steps.vars.outputs.tag }}"
