on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  run:
    name: Run check
    runs-on: ubuntu-latest
    
    steps:       
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
      
      - name: Create local branch
        run: |
          git checkout -b "update/${{ steps.vars.outputs.tag }}"
      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          branch: "update/${{ steps.vars.outputs.tag }}"
