name: Generate

on:
  push:
    branches:
    - citest

jobs:
  get_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: cicd_test
        
      - name: Get latest tag
        id: latest_tag
        run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Use latest tag
        run: echo "Latest tag is ${{ steps.latest_tag.outputs.tag }}"
