on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
# jobs:
#   run:
#     name: Run check
#     runs-on: ubuntu-latest
    
#     steps:       
#       - name: Checkout repo
#         uses: actions/checkout@v3
#         with:
#           ref: master
          
#       - name: Set output
#         id: vars
#         run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
#       - name: Create local branch
#         run: |
#           git checkout -b "update/${{ steps.vars.outputs.tag }}"
          
#       - name: Push branch
#         uses: ad-m/github-push-action@master
#         with:
#           branch: "update/${{ steps.vars.outputs.tag }}"
