on:
  push:
    branches:
    - citest

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: citest

      - name: Reset config environment
        run: |
          echo "hi3" > test.text

      - name: overlap commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 테스트 커밋입니다
          branch: update/confing/develop-enviroment
          create_branch: true

      # - name: Create branch
      #   run: |
      #     git checkout -b "update/confing/develop-enviroment"
          
      # - name: Push branch
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: "update/confing/develop-enviroment"

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Develop pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "update/confing/develop-enviroment"
          destination_branch: "develop"
          pr_title: "Update develop 최신화"

      # - name: Create branch
      #   run: |
      #     git checkout -b "update/confing/develop-enviroment"

      # - name: overlap commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 테스트 커밋입니다
      #     branch: update/confing/develop-enviroment
      #     create_branch: true

      # - name: Push branch
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: "update/confing/develop-enviroment"
