name: Fetch and Display Result

on:
  push:
    branches:
      - update/**

jobs:
  get-feature-branches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: List Branches
      run: |
        BRANCH_LIST=$(git branch -r --format '%(refname:short)' | sed 's/^origin\///' | grep -E '^feature/.+/base$')
        echo "{{$BRANCH_LIST}} 하하하하하하하"