name: Fetch and Display Result

on:
  push:
    branches:
      - update/**

jobs:
  get_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Branches
        id: list_branches
        run: |
          echo "BRANCHES=$(git ls-remote --heads origin | awk -F/ '$3 == "feature" && $5 == "base" {print $4}' | grep -E '^AAA-[0-9]+$' | tr '\n' ','
)" >> $GITHUB_ENV

      - name: Display Branches
        run: |
          echo "Branches: ${{ env.BRANCHS }}"

