name: Fetch and Display Result

on:
  push:
    branches:
      - update/**

jobs:
  get_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Branches
        run: |
          git ls-remote --heads origin | awk -F/ '{print substr($0, index($0,$3))}'
          echo "===================="
          git ls-remote --heads origin | awk -F/ '{print $4}'

# jobs:
#   get-feature-branches:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
      
#     - name: List Branches
#       run: |
#         BRANCH_LIST=$(git branch -r --format '%(refname:short)' | sed 's/^origin\///' | grep -E '^feature/.+/base$')
#         echo "$BRANCH_LIST"