name: Fetch and Display Result

on:
  push:
    branches:
      - update/**

jobs:
  get_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Branches
        id: list_branches
        run: |
          echo "::set-output name=branches::$(git ls-remote --heads origin | awk -F/ '{print substr($0, index($0,$3))}' | tr '\n' ',')"

      - name: Display Branches
        run: |
          echo "Branches: ${{ steps.list_branches.outputs.branches }}"
