name: Fetch and Display Result

on:
  push:
    branches:
      - citest

jobs:
  fetch_and_display:
    name: Fetch and Display Result
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Fetch Result
        id: fetch
        run: |
          result=$(curl https://new-version-evht3pdjia-uc.a.run.app/?version=2.23.010)
          echo "response from curl=$result"
          