# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Configuration Check

on:
  push: 
    branches: [ develop ]

jobs:
  run:
    name: Run check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Test
        run: echo "123"
      
      - uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: feelsodev
          committer_email: swdoriz@gmail.com
          new_branch: testbranch
          
          
