# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "cicd_test" ]

jobs:
  build:

    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '13.4.1' }}
      XC_WORKSPACE: ${{ 'DrinkSomeWater.xcworkspace' }}
      XC_SCHEME: ${{ 'DrinkSomeWater' }}
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Version
      run: ls -n /Applications/ | grep Xcode
    - name: cocoapods install
      run: pod install
    - name: Build
      run: Run ls -n /Applications/ | grep Xcode
    - name: Run tests
      run: xcodebuild clean test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination "platform=iOS Simulator,name=iPhone 11"
