# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "cicd_test" ]

jobs:
  build:

    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '14.0.1' }}
      XC_WORKSPACE: ${{ 'DrinkSomeWater.xcworkspace' }}
      XC_SCHEME: ${{ 'DrinkSomeWater' }}
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - name: cocoapods install
      run: pod install
    - name: Build
      run: echo Build!! DrinkSomeWater
    - name: Run tests
      run: xcodebuild clean test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination "platform=iOS Simulator,name=iPhone 14 Pro"
