# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Configuration Check

on:
  push: 
    branches: [ develop ]

jobs:
  run:
    name: Run check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Test
        run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          ls -al
          echo -e "tetst" > test.text
          
      
      - name: overlap commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 테스트 커밋입니다
          branch: release
