# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "cicd_test" ]

jobs:
  build-ios:

    runs-on: self-hosted
    env:
      XC_VERSION: ${{ '14.0.1' }}
      XC_WORKSPACE: ${{ 'DrinkSomeWater.xcworkspace' }}
      XC_SCHEME: ${{ 'DrinkSomeWater' }}
      
      XC_ARCHIVE_PATH:  ${{ 'DrinkSomeWater.xcarchive' }}
      XC_EXPORT_PATH: ${{ './artifacts' }}
      PROJECT_ROOT_PATH: ${{ 'DrinkSomeWater' }}
      
      KEYCHAIN: ${{ 'test.keychain' }}
      
      DECRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/once.p12' }}
      ENCRYPTED_CERTS_FILE_PATH: ${{ '.github/secrets/once.p12.gpg' }}
      
      DECRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/once.mobileprovision' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ '.github/secrets/once.mobileprovision.gpg' }}
      
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }}    
      PROVISION_ENCRYPTION_PWD: ${{ secrets.PROVISION_ENCRYPTION_PWD }}     
      CERTS_EXPORT_PWD: ${{ secrets.CERTS_EXPORT_PWD }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Xcode Version
      run: ls -n /Applications/ | grep Xcode
    
    - name: Cocoapod # 프로젝트에서 Cocoapod을 사용하지 않는다면 빼도 됩니다.
      run: pod install
      
    - name: Build
      run: echo Build!! DrinkSomeWater

    - name: Run tests
      run: xcodebuild clean test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination "platform=iOS Simulator,name=iPhone 11"
      
